server:
  port: 10010
spring:
  application:
    name: leyou-gateway
zuul:
  prefix: /api
  routes:
    leyou-item-service: /item/**
    leyou-item-upload:  /upload/**
    search-service:    /search/**
    user-service:      /user/**
    auth-service:      /auth/**
    cart-service:      /cart/**
  ignored-services:    #设置服务路由的忽略
    - leyou-item-service
    - leyou-item-upload
    - search-service
    - user-service
    - auth-service
    - cart-service
  sensitive-headers:    #什么都不写，就是关闭zuul的敏感头过滤信息，在Token那使用了


#hystrix就是衡量ribbon的尺子，所以时间必须大于ribbon的总和
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 500    #ribbon连接超时时长
  ReadTimeout: 2000       #ribbon读取超时时长
  MaxAutoRetries: 0       #当前服务重试次数
  MaxAutoRetriesNextServer: 3   #切换服务重试次数
  OkToRetryOnAllOperations: false #是否对所有的请求方式都重试，只对get请求重试



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#跨域
ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
  jwt:
    pubKeyPath: F:/heima/rsa/id_rsa.pub  #  # D:/heima/rsa/id_rsa.pub # 公钥地址
    app:
      id: 7       #当前服务的id 网关在表中id是7
      secret: api-gateway    #服务密码，测试阶段使用的是服务的名称
      headerName: heima88    #请求头名称
    user:
      cookieName: LY_TOKEN

  filter:                         #白名单
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/auth/verify