server:
  port: 8084

spring:
  application:
    name: page-service

  thymeleaf:
    cache: false  #是否缓存

  rabbitmq: #配置rabbitMq的消息
    host: 192.168.2.128
    virtual-host: /leyou
    username: leyou
    password: leyou


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间

ly:
  static:
   itemDir: E:/nginx-1.12.2/nginx-1.12.2/html/item
   itemTemplate: item