server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.2.128
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyID: LTAI4FmhJA2e3vE4vfBdYfr1 # 你自己的accessKeyId
    accessKeySecret: 1hI2FYJEEVIWxpZYiVPZGoE56ijT0f # 你自己的AccessKeySecret
    signName: 小不点是最棒的   # 签名名称
    verifyCodeTemplate: SMS_178451936 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id